### ISSUE TITLE
本画像を登録機能の作成

### ISSUE THREAD

**Issue by se-tomo** [Racmy/book-management#22]
本の画像を登録できるようにする。
画像を選択しなかった場合はNoimageを表示

【完了条件】
・本の画像が登録できること
・選択しなかった場合はデフォルトの画像

**Comment by yutoyoden** [comment]
本が登録できないときはファイルを保存しないようにする．

**Comment by yutoyoden** [comment]
jqueryのsqript(画像取り込み)修正

**Comment by se-tomo** [comment]
いったん完成したので、developにマージしました。
issue#31でコードレビュー後のリファクタリングをしてください。
