### ISSUE TITLE
ログアウト機能の作成

### ISSUE THREAD

**Issue by se-tomo** [Racmy/book-management#54]
# 目的
ログインを維持することは、危険のため、ログアウトの機能を作成する。

# 機能
各ヘッダーのログアウトボタンを押下すると、ユーザ情報のセッションを削除する

# 完了条件
- 画面遷移図通り遷移することを確認する
- コードレビュー済

**Comment by yutoyoden** [comment]
issue＃54にて，コミット済み
コードレビューおよび，developへのマージは未
