### ISSUE TITLE
アカウント登録機能の作成

### ISSUE THREAD

**Issue by se-tomo** [Racmy/book-management#55]
# 目的
ユーザが自分でアカウントを作成できるようにするために本機能を作成する

# 機能
アカウント登録画面から、アカウント情報を入力後、アカウントを登録する機能を作成してください。
入力したメールアドレスに対して正規表現でチェック等の入力チェックをしてください。
登録完了時に、登録したメールアドレスに対してメールを一通送信してください。
メールが送信できた場合は有効化フラグを立ててください。
メールが送信できない場合は有効化フラグは立てないでください。

# 完了条件

- コードレビュー済
- 画面遷移図通り遷移することを確認する
- 作成したアカウントでログインできることを確認してください。

**Comment by se-tomo** [comment]
画像は登録できないが、ユーザ登録可能な状態になっている。

**Comment by yutoyoden** [comment]
画像は，のちの実装に回し，今回はクローズ
