### ISSUE TITLE
/book/***のURLの遷移にログインチェックを行う。

### ISSUE THREAD

**Issue by se-tomo** [Racmy/book-management#60]
# 目的
ログインしていないユーザが、/book/***のURLに遷移した場合、エラーになってしまうため、エラーハンドリングする必要がある。

# 機能
・/book/***のURLに非ログインユーザが遷移しようとした場合は、ログイン画面に遷移するようにしてください。
・具体的には、/book/***のハンドラーの前処理に共通のログインチェックを作成してください
・ログインチェックは、セッションにユーザ情報が格納されていることを確認することで行ってください。
・エラーメッセージは「ログインを行ってください。」

# 完了条件
・非ログイン状態で/book/***のURLを直接入力し、ログイン画面へ遷移すること確認する。
・コードレビュー済

**Comment by yutoyoden** [comment]
実装済み，レビューまだ
